name: Notify Parent Repo

on:
  push:
    branches:
      - main

jobs:
  notify-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent-repo
        uses: actions/checkout@v4
        with:
          repository: pozda/jambox-project  # Replace with your parent repo
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH private key
          submodules: true                       # Ensure submodules are checked out

      - name: Update submodules in parent-repo
        run: |
          git submodule update --remote --merge
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Update submodule to latest main" || echo "No changes to commit"
          git push