name: Update Project Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Project Repo
        uses: actions/checkout@v4
        with:
          repository: jambox-digital/jambox-project
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          submodules: true
          fetch-depth: 0

      - name: Update Submodule Reference
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodule to latest commit in library" || echo "No changes to commit"
          git push origin main
